config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :deals do
      resources :orders, :controller => "deals/orders"
      member do
        put :confirm
      end
    end
  end
  resources :deals
end

app/models/spree/deal.rb
module Spree
  class Deal < ActiveRecord::Base
    belongs_to :product, :dependent => :destroy
    delegate_belongs_to :product, :list_price, :price

    validates_presence_of :name, :product_id, :starts_at, :expires_at
    validate      :product_should_exist

    before_create :duplicate_product
    after_create :enqueue_expiration_job
    after_save   :enqueue_start_job, :if => "starts_at_changed? and !active?"

    scope :active, where(:state => "active")
    scope :for, lambda { |product| where(:product_id => product.try(:id)) }

    state_machine :initial => 'created', :use_transactions => false do
      event :expire do
        transition :from => 'active', :to => 'expired'
      end

      event :start do
        transition :from => 'created', :to => 'active', :if => "starts_at <= Time.now"
      end

      event :confirm do
        transition :from => 'expired', :to => 'complete'
      end

      event :void do
        transition :from => 'expired', :to => 'void'
      end

      after_transition :to => 'expired', :do => :notify_admin
      after_transition :to => 'complete', :do => :enqueue_confirm_job
    end

    def notify_admin
      DealMailer.expiration_email(self).deliver
    end

    def percent
      product.deal_percent
    end

    def met?
      count_quantity >= minimum_quantity
    end

    def count_quantity
      @count_quantity ||= InventoryUnit.where(:variant_id => product.variants_including_master_ids).count
    end

    def left_quantity
      minimum_quantity - count_quantity
    end

    def enqueue_expiration_job
      Delayed::Job.enqueue(Deals::ExpireJob.new(id), :run_at => expires_at)
    end

    def enqueue_start_job
      unless start
        Delayed::Job.enqueue(Deals::StartJob.new(id), :run_at => starts_at)
      end
    end

    def enqueue_confirm_job
      Delayed::Job.enqueue(Deals::ConfirmJob.new(id))
    end

    #TODO optimize this by sql join
    def orders
      @orders ||= Order.deal_pending.select { |order| order.inventory_units.collect(&:variant).collect(&:product_id).include?(product_id) }
    end

    def order_ids
      orders.collect(&:id)
    end

    def product_should_exist
      errors.add(:product_id, "Product doesnt exist") unless Product.exists?(product_id)
    end

    def duplicate_product
      prod = Product.find(product_id)
      self.product_id = prod.duplicate(:prefix => "Deal ").id
    end
  end
end

app/controllers/spree/admin/deals/orders_controller.rb
module Spree
  module Admin
    class Deals::OrdersController < BaseController
      def index
        @search = Order.metasearch(params[:search])
        @deal = Deal.find(params[:deal_id])
        @orders = @deal.orders
      end
    end
  end
end

app/controllers/spree/admin/deals_controller.rb
module Spree::Admin
  class DealsController < ResourceController
    def index
      respond_with(@collection) do |format|
        format.html
        format.json { render :json => json_data }
      end
    end

    def new
      @deal = Spree::Deal.new
    end

    def confirm
      @deal = Spree::Deal.find(params[:id])
      flash.notice = t("deal.complete") if @deal.confirm
      redirect_to admin_deals_path
    end
  end
end

app/controllers/spree/deals_controller.rb
module Spree
  class DealsController < BaseController
    respond_to :html
    HTTP_REFERER_REGEXP = /^https?:\/\/[^\/]+\/t\/([a-z0-9\-\/]+)$/

    def index
      @deals = Deal.active.all
    end

    def show
      @deal = Deal.find(params[:id])

      @product = @deal.product
      #TODO DRY this, comes from ProductsController#show
      @variants = Variant.active.includes([:option_values, :images]).where(:product_id => @deal.product_id)
      @product_properties = ProductProperty.includes(:property).where(:product_id => @deal.product_id)

      referer = request.env['HTTP_REFERER']

      if referer && referer.match(HTTP_REFERER_REGEXP)
        @taxon = Taxon.find_by_permalink($1)
      end

      respond_with(@deal)
    end
  end
end

app/helpers/spree/admin/deals/orders_helper.rb
module Spree::Admin::Deals::OrdersHelper
end

app/helpers/spree/admin/deals_helper.rb
module Spree::Admin::DealsHelper
end

app/helpers/spree/deals_helper.rb
module Spree::DealsHelper
  def t_unit_state(unit)
    unit_scope = [:inventory_unit_state]
    if deal = unit.variant.try(:product).try(:deal)
      unit_scope << :deal
      return t deal.state, :scope => unit_scope unless deal.complete?
      unit_scope << deal.state.to_sym
    else
      unit_scope << :base
    end
    t unit.state, :scope => unit_scope
  end
end

app/views/spree/admin/deals/orders/index.html.erb
<div class='toolbar order-links'>
  <%= button_link_to t(:new_order), new_admin_order_url, :icon => 'add', :id => 'admin_new_order' %>
</div>

<%= render :partial => 'spree/admin/shared/order_sub_menu' %>

<h1><%= t(:listing_orders) %></h1>

<table class="index" id="listing_orders" data-hook>
  <thead>
    <tr data-hook="admin_orders_index_headers">
      <% if @show_only_completed %>
        <th><%= sort_link @search, :completed_at, t('activerecord.attributes.order.completed_at') %></th>
      <% else %>
        <th><%= sort_link @search, :created_at,   t(:order_date) %></th>
      <% end %>
      <th><%= sort_link @search, :number,         t(:order_number) %></th>
      <th><%= sort_link @search, :state,          t(:status) %></th>
      <th><%= sort_link @search, :payment_state,  t(:payment_state) %></th>
      <th><%= sort_link @search, :shipment_state, t(:shipment_state) %></th>
      <th><%= sort_link @search, :email,          t(:customer) %></th>
      <th><%= sort_link @search, :total,          t(:total) %></th>
      <th data-hook="admin_orders_index_header_actions"></th>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr data-hook="admin_orders_index_rows">
      <td><%= l (@show_only_completed ? order.completed_at : order.created_at).to_date %></td>
      <td><%= link_to order.number, admin_order_path(order) %></td>
      <td><%= t("order_state.#{order.state.downcase}") %></td>
      <td><%= link_to t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) if order.payment_state %></td>
      <td><%= link_to t("shipment_states.#{order.shipment_state}"), admin_order_shipments_path(order) if order.shipment_state %></td>
      <td><%= order.email %></td>
      <td><%= number_to_currency order.total %></td>
      <td class='actions' data-hook="admin_orders_index_row_actions">
        <%= link_to_edit_url edit_admin_order_path(order), :title => "admin_edit_#{dom_id(order)}" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>


<% content_for :sidebar do %>
  <%= render "spree/admin/deals/sidebar" %>

  <div class="box" data-hook="admin_orders_index_search">
    <h3><%= t(:search) %></h3>
    <%= form_for [:admin, @search] do |f| %>
      <%= label_tag nil, t(:date_range) %><br />
      <div class="date-range-filter">
        <div class="left sub-field">
          <%= f.text_field :created_at_greater_than, :class => 'datepicker' %><br />
          <%= label_tag nil, t(:start), :class => 'sub' %>
        </div>
        <div class="right sub-field">
          <%= f.text_field :created_at_less_than, :class => 'datepicker' %><br />
          <%= label_tag nil, t(:stop), :class => 'sub' %>
        </div>
      </div>

      <p><%= label_tag nil, t(:status) %><br />
      <%= f.select :state_equals, Spree::Order.state_machines[:state].states.collect {|s| [t("order_state.#{s.name}"), s.value]}, {:include_blank => true} %></p>

      <p>
        <%= label_tag nil, t(:order_number) %><br />
        <%= f.text_field :number_like, :size => 25 %>
      </p>
      <p>
        <%= label_tag nil, t(:email) %><br />
        <%= f.text_field :email_like, :size => 25 %>
      </p>
      <p>
        <%= label_tag nil, t(:first_name_begins_with) %><br />
        <%= f.text_field :bill_address_firstname_starts_with, :size => 25 %>
      </p>
      <p>
        <%= label_tag nil, t(:last_name_begins_with) %><br />
        <%= f.text_field :bill_address_lastname_starts_with, :size => 25 %>
      </p>
      <p>
        <%= f.check_box :completed_at_is_not_null, {:checked => @show_only_completed}, '1', '' %>
        <%= label_tag nil, t(:show_only_complete_orders) %>
      </p>
      <div data-hook="admin_orders_index_search_buttons">
        <p><%= button t(:search) %></p>
      </div>
    <% end %>
  </div>
<% end %>