config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :deals do
      resources :orders, :controller => "deals/orders"
      member do
        put :confirm
      end
    end
  end
  resources :deals
end

app/models/spree/deal.rb
module Spree
  class Deal < ActiveRecord::Base
    belongs_to :product, :dependent => :destroy
    delegate_belongs_to :product, :list_price, :price

    validates_presence_of :name, :product_id, :starts_at, :expires_at
    validate      :product_should_exist

    before_create :duplicate_product
    after_create :enqueue_expiration_job
    after_save   :enqueue_start_job, :if => "starts_at_changed? and !active?"

    scope :active, where(:state => "active")
    scope :for, lambda { |product| where(:product_id => product.try(:id)) }

    state_machine :initial => 'created', :use_transactions => false do
      event :expire do
        transition :from => 'active', :to => 'expired'
      end

      event :start do
        transition :from => 'created', :to => 'active', :if => "starts_at <= Time.now"
      end

      event :confirm do
        transition :from => 'expired', :to => 'complete'
      end

      event :void do
        transition :from => 'expired', :to => 'void'
      end

      after_transition :to => 'expired', :do => :notify_admin
      after_transition :to => 'complete', :do => :enqueue_confirm_job
    end

    def notify_admin
      DealMailer.expiration_email(self).deliver
    end

    def percent
      product.deal_percent
    end

    def met?
      count_quantity >= minimum_quantity
    end

    def count_quantity
      @count_quantity ||= InventoryUnit.where(:variant_id => product.variants_including_master_ids).count
    end

    def left_quantity
      minimum_quantity - count_quantity
    end

    def enqueue_expiration_job
      Delayed::Job.enqueue(Deals::ExpireJob.new(id), :run_at => expires_at)
    end

    def enqueue_start_job
      unless start
        Delayed::Job.enqueue(Deals::StartJob.new(id), :run_at => starts_at)
      end
    end

    def enqueue_confirm_job
      Delayed::Job.enqueue(Deals::ConfirmJob.new(id))
    end

    #TODO optimize this by sql join
    def orders
      @orders ||= Order.deal_pending.select { |order| order.inventory_units.collect(&:variant).collect(&:product_id).include?(product_id) }
    end

    def order_ids
      orders.collect(&:id)
    end

    def product_should_exist
      errors.add(:product_id, "Product doesnt exist") unless Product.exists?(product_id)
    end

    def duplicate_product
      prod = Product.find(product_id)
      self.product_id = prod.duplicate(:prefix => "Deal ").id
    end
  end
end

app/controllers/spree/admin/deals/orders_controller.rb
module Spree
  module Admin
    class Deals::OrdersController < BaseController
      def index
        @search = Order.metasearch(params[:search])
        @deal = Deal.find(params[:deal_id])
        @orders = @deal.orders
      end
    end
  end
end

app/controllers/spree/admin/deals_controller.rb
module Spree::Admin
  class DealsController < ResourceController
    def index
      respond_with(@collection) do |format|
        format.html
        format.json { render :json => json_data }
      end
    end

    def new
      @deal = Spree::Deal.new
    end

    def confirm
      @deal = Spree::Deal.find(params[:id])
      flash.notice = t("deal.complete") if @deal.confirm
      redirect_to admin_deals_path
    end
  end
end

app/controllers/spree/deals_controller.rb
module Spree
  class DealsController < BaseController
    respond_to :html
    HTTP_REFERER_REGEXP = /^https?:\/\/[^\/]+\/t\/([a-z0-9\-\/]+)$/

    def index
      @deals = Deal.active.all
    end

    def show
      @deal = Deal.find(params[:id])

      @product = @deal.product
      #TODO DRY this, comes from ProductsController#show
      @variants = Variant.active.includes([:option_values, :images]).where(:product_id => @deal.product_id)
      @product_properties = ProductProperty.includes(:property).where(:product_id => @deal.product_id)

      referer = request.env['HTTP_REFERER']

      if referer && referer.match(HTTP_REFERER_REGEXP)
        @taxon = Taxon.find_by_permalink($1)
      end

      respond_with(@deal)
    end
  end
end

app/helpers/spree/admin/deals/orders_helper.rb
module Spree::Admin::Deals::OrdersHelper
end

app/helpers/spree/admin/deals_helper.rb
module Spree::Admin::DealsHelper
end

app/helpers/spree/deals_helper.rb
module Spree::DealsHelper
  def t_unit_state(unit)
    unit_scope = [:inventory_unit_state]
    if deal = unit.variant.try(:product).try(:deal)
      unit_scope << :deal
      return t deal.state, :scope => unit_scope unless deal.complete?
      unit_scope << deal.state.to_sym
    else
      unit_scope << :base
    end
    t unit.state, :scope => unit_scope
  end
end

app/views/spree/admin/deals/_form.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @deal } %>
<fieldset id="general_fields">
  <legend><%= t(:general) %></legend>

  <%= form.field_container :name do %>
    <%= form.label :name %><br />
    <%= form.text_field :name %>
  <% end %>

  <%= form.field_container :description do %>
    <%= form.label :description %><br />
    <%= form.text_area :description, :style => 'height:50px;' %>
  <% end %>

  <%= t('product_rule.choose_products') %><br />
  <%= form.label :product, t(:product) %><br />
  <%= product_picker_field "#{form.object_name}[product_id]", form.object.product_id.to_s %>

  <%= form.field_container :minimum_quantity do %>
    <%= form.label :minimum_quantity, t(:minimum_quantity) %><br />
    <%= form.text_field :minimum_quantity %>
  <% end %>
</fieldset>
<fieldset id="expiry_fields">
  <legend><%= t(:expiry) %></legend>


  <p id="starts_at_field">
    <%= form.label :starts_at %>
    <%= form.text_field :starts_at, :class => 'datepicker' %>
  </p>
  <p id="expires_at_field">
    <%= form.label :expires_at %>
    <%= form.text_field :expires_at, :class => 'datepicker' %>
  </p>
</fieldset>

<%= form.submit "Create" %>

app/views/spree/admin/deals/_form_product.html.erb
<fieldset>
  <%= form.label :list_price, t(:list_price) %>
  <%= form.text_field :list_price %><br />
  <%= form.label :price, t(:price) %>
  <%= form.text_field :price %>
  <%= form.submit "Update" %>
</fieldset>

app/views/spree/admin/deals/_sidebar.html.erb
<div id="deal_tab_summary" data-hook>
  <h3 id="deal_number" data-hook><%= t("deal.name") %> #<%= @deal.id %></h3>
  <h5 id="deal_status" data-hook><%= t(:status) %>: <%# t(@deal.state, :scope => :deal_state) %></h5>
  <br class="clear" />
</div>
<br class="clear" />

<ul class="sidebar" data-hook="admin_deal_tabs">
  <li<%== ' class="active"' if controller.controller_name == 'deals' %>>
    <%= link_to t("deal.name"), edit_admin_deal_url(@deal) %>
  </li>
  <li<%== ' class="active"' if controller.controller_name == 'orders' %>>
    <%= link_to t(:orders), admin_deal_orders_url(@deal) %>
  </li>
</ul>

app/views/spree/admin/deals/edit.html.erb
<h1><%= t(:editing_deal) %></h1>

<%= form_for [:admin, @deal] do |f| %>
  <%= render f %>
<% end %>

<%= form_for [:admin, @deal.product] do |f| %>
  <%= render "form_product", :form => f %>
<% end %>

<% content_for :sidebar do %>
  <%= render "sidebar" %>
<% end %>

app/views/spree/admin/deals/index.html.erb
<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li id="new_deal_link">
      <%= button_link_to t(:new_deal), spree.new_admin_deal_path, {:icon => 'add', :id => 'admin_new_deal'} %>
    </li>
  </ul>
  <br class="clear" />
</div>

<h1><%= t(:listing_deals) %></h1>

<div id="new_deal" data-hook></div>

<table class="index" id="listing_deals">
  <tr data-hook="admin_deals_index_headers">
    <th><%= t(:name) %></th>
    <th><%= t(:description) %></th>
    <th><%= t(:minimum_quantity) %></th>
    <th><%= t(:product_name) %></th>
    <th><%= t(:product_list_price) %></th>
    <th><%= t(:product_price) %></th>
    <th><%= t(:product_deal) %></th>
    <th data-hook="admin_deals_index_header_actions"></th>
  </tr>
<% @collection.each do |deal| %>
  <tr <%= "style='color: red;'" unless deal.met? %> id="<%= dom_id deal %>" data-hook="admin_deals_index_rows">
    <td><%= deal.name %></td>
    <td><%= deal.description %></td>
    <td><%= deal.minimum_quantity %></td>
    <td><%= deal.product.name %></td>
    <td><%= deal.product.list_price %></td>
    <td><%= deal.product.price %></td>
    <td><%= number_to_percentage(deal.product.deal_percent, :precision => 0) %></td>
    <td>
      <%= link_to_edit deal %> &nbsp;
      <%= link_to_delete deal %>
      <%= button_link_to "Confirm", confirm_admin_deal_path(deal), :method => :put, :confirm => t(:are_you_sure) if deal.expired? %>
    </td>
  </tr>
<% end %>
</table>

app/views/spree/admin/deals/new.html.erb
<h1><%= t(:new_deal) %></h1>

<%= form_for [:admin, @deal] do |f| %>
  <%= render f %>
<% end %>